# CALCULATOR
a = int(input('Enter value of number one : '))
b = int(input("Enter value number two : "))
print("sum is ", (a + b))
print("sub is ", (a - b))
print("multiplication is ", (a * b))
print("division is ", (a / b))
print("a > b", (a > b))
print("a < b", (a < b))
print("a >= b", (a >= b))
print("a <= b", (a <= b))
print("a == b", (a == b))
print("a & b", (a & b))
print("a | b", (a | b))
